# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'learnOCItem' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for learnOCItem
  pod 'FMDB', '~> 2.7.2'
  pod 'Masonry'
  target 'learnOCItemTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'learnOCItemUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
